name: Run Unit Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Unit Tests

    steps:
      - name: Установить проект
        uses: actions/checkout@v6

      - name: Установить Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Запустить тесты
        run: |
          python -m unittest discover

  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy on the server

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd CICD
            git pull